// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD11EEUu4wbRyB0hcBgGbHlS1A5JKQHuaE',
    appId: '1:676207571399:web:484ffeca6205856e26e9e2',
    messagingSenderId: '676207571399',
    projectId: 'ajwad-elnass',
    authDomain: 'ajwad-elnass.firebaseapp.com',
    storageBucket: 'ajwad-elnass.firebasestorage.app',
    measurementId: 'G-9XMESQ5MYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjYbPsK-8TUBWUotEziGTk3phNjvBjW-E',
    appId: '1:676207571399:android:e8a68256caeda6bb26e9e2',
    messagingSenderId: '676207571399',
    projectId: 'ajwad-elnass',
    storageBucket: 'ajwad-elnass.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk6ZVLvofl68nB3HW2L6FlM4NzEPbsJUE',
    appId: '1:676207571399:ios:f8fb3fc18dd02e9f26e9e2',
    messagingSenderId: '676207571399',
    projectId: 'ajwad-elnass',
    storageBucket: 'ajwad-elnass.firebasestorage.app',
    iosBundleId: 'com.hth.ajwadElnass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk6ZVLvofl68nB3HW2L6FlM4NzEPbsJUE',
    appId: '1:676207571399:ios:f8fb3fc18dd02e9f26e9e2',
    messagingSenderId: '676207571399',
    projectId: 'ajwad-elnass',
    storageBucket: 'ajwad-elnass.firebasestorage.app',
    iosBundleId: 'com.hth.ajwadElnass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD11EEUu4wbRyB0hcBgGbHlS1A5JKQHuaE',
    appId: '1:676207571399:web:11080c824e9bbbad26e9e2',
    messagingSenderId: '676207571399',
    projectId: 'ajwad-elnass',
    authDomain: 'ajwad-elnass.firebaseapp.com',
    storageBucket: 'ajwad-elnass.firebasestorage.app',
    measurementId: 'G-Q7DPRXNZT0',
  );
}
